[project]
name = "pixi_py_copy"
description = "Add a short description here"
authors = [{name = "Andre Medina", email = "AndreMedina@hotmail.com.au"}]
readme="README.md"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pixi_py_copy"]

[tool.hatch.build.targets.wheel.sources]
"pixi_py_copy" = "pixi_py_copy"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../.."

[tool.hatch.metadata]
allow-direct-references = true
